<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 9</b></center>    
<left><b><h3>Roll No. : 125</b></left>  
<left><b><h3>Name : Mohit Sojitra</b></left>   
<pre>    

### 1. Create a NumPy array of 10 student marks and display its `dtype`, `size`, `ndim`, `shape`, `itemsize`, and `nbytes`.

In [ ]:
pip install numpy

In [11]:
import numpy as np

stu=np.arange(1,11)
arr=np.array([10,20,30,40,50])
print(stu)
print(arr)
print(stu.dtype)
print(stu.size)
print(stu.ndim)
print(stu.shape)
print(stu.itemsize)
print(stu.nbytes)

[ 1  2  3  4  5  6  7  8  9 10]
[10 20 30 40 50]
int64
10
1
(10,)
8
80


### 2.Create NumPy arrays using zeros, ones, full, arange, linspace, and identity functions.

In [12]:
import numpy as np

s=np.zeros((3,3),dtype=int)
s2=np.ones((3,3),dtype=int)
s3=np.full((2,2),25)
s4=np.arange(1,10)
s5=np.linspace(1,50,3)

print(s)
print(s2)
print(s3)
print(s4)
print(s5)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[25 25]
 [25 25]]
[1 2 3 4 5 6 7 8 9]
[ 1.  25.5 50. ]


### 3. Create an array of numbers from 1 to 25, reshape it into a 5×5 matrix, and display its transpose.

In [16]:
import numpy as np

arr=np.arange(1,26,1).reshape(5,5)
print("Original Array ")
print(arr)
print("Transpose Array ")
print(arr.T)

Original Array 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Transpose Array 
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


### 4. Generate marks of 20 students randomly between 0 and 100 and find their highest, lowest, and average marks.

In [19]:
import numpy as np

arr=np.random.randint(0,100,20)
print(arr)
print("Highest : ",arr.max())
print("Lowest : ",arr.min())
print("Average : ",arr.mean())

[187 171 194 174  58 111  43  60  32  82  34  12  98  51  99 163 134 151
  56  37]
Highest :  194
Lowest :  12
Average :  97.35


### 5. Generate random numbers using `rand()`, `randn()`, `uniform()`, and `normal()`. Use a seed to reproduce the results.

In [21]:
import numpy as np

arr1=np.random.randint(1,5,3)
arr2=np.random.rand(3)
arr3=np.random.uniform(1,5,3)
arr4=np.random.normal(1,5,3)

print(arr1)
print(arr2)
print(arr3)
print(arr4)


[4 3 2]
[0.90180075 0.4517636  0.79705401]
[4.38347849 2.52546867 2.69019358]
[-0.86326958  3.61809408  3.47231495]


### 6. Given roll numbers 101–120, randomly select 5 students without replacement and demonstrate shuffling and permutation.

In [27]:
import numpy as np

arr=np.random.randint(101,121,5)
print(arr)
np.random.shuffle(arr)
print(arr)
np.random.permutation(arr)
print(arr)


[119 105 120 115 109]
[119 109 105 115 120]
[119 109 105 115 120]


### 7. Given marks of 15 students, calculate sum, mean, median, minimum, maximum, variance, and standard deviation.

In [42]:
arr1=np.random.randint(1,16,15)

print(arr1)

print("Sum : ",arr1.sum())
print("Mean : ",arr1.mean())
print("Median : ",np.median(arr1))
print("Min : ",arr1.min())
print("Max : ",arr1.max())
print("Var : ",np.var(arr1))
print("Std : ",np.std(arr1))

[ 1 13  9  3  7  5 15 14  4  2 13 13 13 10 14]
Sum :  136
Mean :  9.066666666666666
Median :  10.0
Min :  1
Max :  15
Var :  22.995555555555555
Std :  4.795368135561185


### 8. Given daily sales for 10 days, calculate total sales, average sales, cumulative sales, and cumulative product.

In [45]:
import numpy as np

arr=np.random.randint(0,100,10)

print("Sum : ",arr.sum())
print("Mean : ",arr.mean())
print("CumSum : ",arr.cumsum())
print("CumProd : ",arr.cumprod())

Sum :  578
Mean :  57.8
CumSum :  [ 28  61 142 229 299 354 418 491 537 578]
CumProd :  [                28                924              74844
            6511428          455799960        25068997800
      1604415859200    117122357721600   5387628455193600
 220892766662937600]


### 9. Create two NumPy arrays and perform addition, subtraction, multiplication, division, floor division, modulus, and exponentiation.

In [48]:
import numpy as np

arr1=np.random.randint(1,50,5)
arr2=np.random.randint(1,50,5)

print(arr1)
print(arr2)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1 ** arr2)

[19 21 45  3 13]
[46 48 20 38 14]
[65 69 65 41 27]
[-27 -27  25 -35  -1]
[ 874 1008  900  114  182]
[0.41304348 0.4375     2.25       0.07894737 0.92857143]
[0 0 2 0 0]
[19 21  5  3 13]
[ 1022832537  1390169665 -1924594607  -400556711  -523170343]


### 10. Create an unsorted array of student marks and display it in ascending and descending order. Also find the sorted indices.

In [57]:
import numpy as np

arr=np.random.randint(1,100,20)
print("Array -> ",arr)
arr.sort()
print("Asce Sort -> ",arr)
desc=arr[::-1]
print("Desc Sort -> ",desc)
print("Agr Sort -> ",np.argsort(arr))

Array ->  [81  8 94 69 41 28 30 73  1 95 43 27  8 89 91 83 55 43 86 92]
Asce Sort ->  [ 1  8  8 27 28 30 41 43 43 55 69 73 81 83 86 89 91 92 94 95]
Desc Sort ->  [95 94 92 91 89 86 83 81 73 69 55 43 43 41 30 28 27  8  8  1]
Agr Sort ->  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### 11. Given the following NumPy array:
Write a program to display:

- First 5 elements
- Last 4 elements
- Elements from index 2 to 6
- Every alternate element

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [64]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(arr[:5])
print(arr[-1:-5:-1])
print(arr[2:6:1])
print(arr[::2])

[10 20 30 40 50]
[100  90  80  70]
[30 40 50 60]
[10 30 50 70 90]


### 12. Given the following NumPy array:
Write a program to display:

- The array in reverse order
- Every second element in reverse order
- Last 5 elements in reverse order

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [74]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

print(arr[::-1])
print(arr[-1::-2])
print(arr[-6::1])

[50 45 40 35 30 25 20 15 10  5]
[50 40 30 20 10]
[25 30 35 40 45 50]


### 13. Given following NumPy Array:
Write a program to display:

- First two rows
- Last two rows
- Alternate rows
- Rows from index 1 to 3

In [ ]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

In [83]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

print(arr[:2:,::])
print(arr[:-3:-1,::])
print(arr[::2,::])
print(arr[1::,::])

[[10 20 30 40]
 [50 60 70 80]]
[[130 140 150 160]
 [ 90 100 110 120]]
[[ 10  20  30  40]
 [ 90 100 110 120]]
[[ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


### 14. Given following NumPy Array:
Write a program to display:
- First two columns
- Last three columns
- First three rows and last two columns
- A 2×3 sub-array from the center

In [ ]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

In [93]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print(arr[::,:2:])
print(arr[::,-3::])
print(arr[:3:,-2::])
print(arr[1:3:,1:4:])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 4  5]
 [ 9 10]
 [14 15]]
[[ 7  8  9]
 [12 13 14]]


### 15. Given following NumPy Array:
Write a program to display:
- The matrix with rows in reverse order
- The matrix with columns in reverse order
- The matrix with both rows and columns reversed
- Alternate rows and alternate columns

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [98]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(arr[::-1,::])
print(arr[::,::-1])
print(arr[::-1,::-1])
print(arr[::2,::2])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 1  3]
 [ 9 11]]


### 15. Given an array of marks, write a program to display students who scored more than 75 marks.

In [ ]:
marks = np.array([45, 78, 62, 89, 35, 91, 56, 73, 40, 84])

In [102]:
import numpy as np

marks = np.array([45, 78, 62, 89, 35, 91, 56, 73, 40, 84])

for i in marks:
    if(i>75):
        print(i)

marks[marks>75] 

print(marks)

78
89
91
84
[45 78 62 89 35 91 56 73 40 84]


### 16. Given an array, write a program to display elements that are greater than 30 and less than 70.

In [ ]:
arr = np.array([12, 25, 37, 44, 51, 63, 72, 81, 90, 18])

In [108]:
arr = np.array([12, 25, 37, 44, 51, 63, 72, 81, 90, 18])

new_arr=arr[(arr>30) & (arr<70)]

print(new_arr)

[37 44 51 63]


### 17. Given an array, write a program to display elements that are divisible by 5 and greater than 25, and then display elements that are either less than 20 or greater than 45.

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [111]:
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

new_arr=arr[(arr%5==0) & (arr>25)]

print(new_arr)

[30 35 40 45 50 55]
